//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VIBURO.RC
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_VIBUROTYPE                  129
#define IDD_WAECHTER                    130
#define IDD_MAIN                        132
#define IDC_HILFE                       1000
#define IDC_NAME                        1001
#define IDC_PASSWORD                    1002
#define IDC_JAHR                        1009
#define IDC_SPIN_TAG                    1012
#define IDC_STUN                        1013
#define IDC_MIN                         1015
#define IDC_SLIDER                      1017
#define IDC_ADD                         1018
#define IDC_DEL                         1019
#define IDC_ANZEIG_JA                   1020
#define IDC_ANZEIG_NEIN                 1021
#define IDC_STUN_SUM                    1022
#define IDC_GEHALT                      1023
#define IDC_MONAT                       1024
#define IDC_SPIN_STUN                   1025
#define IDC_SPIN_MIN                    1026
#define IDC_TAG                         1027
#define IDC_STATIC124                   1028
#define IDC_RADIO1                      1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
