//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ViBuro.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_VIBURO_FORM                 101
#define IDD_WAECHTER                    102
#define IDS_PROPSHT_CAPTION             103
#define IDD_PROPPAGE1                   104
#define IDD_PROPPAGE2                   105
#define IDD_PROPPAGE3                   106
#define IDD_PROPPAGE4                   107
#define IDD_PROPPAGE5                   108
#define IDD_PROPPAGE6                   109
#define IDR_MAINFRAME                   128
#define IDR_VIBUROTYPE                  129
#define IDR_VIBUROTYPE_AUFGABE          130
#define IDR_VIBUROTYPE_BERICHT          131
#define IDD_MAIN                        132
#define IDD_NEW                         133
#define IDC_HILFE                       1000
#define IDC_SITZUNG_ADD_JA              1000
#define IDC_NAME                        1001
#define IDC_SITZUNG_ADD_NEIN            1001
#define IDC_ADRES_STRASSE               1001
#define IDC_PASSWORD                    1002
#define IDC_ADRES_PLZ                   1002
#define IDCBankBLZ                      1003
#define IDC_Bank_BLZ                    1003
#define IDCBankGELDINSTITUT             1004
#define IDC_ADRES_TELEFON               1004
#define IDC_Bank_GELDINSTITUT           1004
#define IDCBankSTADT                    1005
#define IDC_Bank_STADT                  1005
#define IDC_ADRES_STADT                 1006
#define IDCBankKONTO                    1006
#define IDC_Bank_KONTO                  1006
#define IDC_JOB_COMBO                   1008
#define IDC_JAHR                        1009
#define IDC_NAME_NAME                   1009
#define IDC_NAME_VORNAME                1010
#define IDC_NAME_TAG                    1011
#define IDC_SPIN_TAG                    1012
#define IDC_NAME_MONAT                  1012
#define IDC_STUN                        1013
#define IDC_NAME_JAHR                   1013
#define IDC_MIN                         1015
#define IDC_SLIDER                      1017
#define IDC_ADD                         1018
#define IDC_DEL                         1019
#define IDC_ANZEIG_JA                   1020
#define IDC_ANZEIG_NEIN                 1021
#define IDC_STUN_SUM                    1022
#define IDC_GEHALT                      1023
#define IDC_MONAT                       1024
#define IDC_SPIN_STUN                   1025
#define IDC_SPIN_MIN                    1026
#define IDC_TAG                         1027
#define IDC_STATIC124                   1028
#define ID_ARBEIT_AUFGABE               32771
#define IDM_AUFGABE                     32771
#define ID_ARBEIT_BERICHT               32772
#define IDM_BERICHT                     32772
#define ID_ARBEIT_EINSTELLUNGEN         32773
#define ID_SITZUNG_DAUER                32774
#define ID_TIMER                        32775
#define ID_TIMER_STUN_EINGAB            32776
#define ID_ARBEIT_TEST                  32777
#define ID_ARBEIT_TEST1                 32778
#define ID_ARBEIT_TEST2                 32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
